### ISSUE TITLE
Add cancellation action

### ISSUE THREAD

**Issue by arieswandari** [janosgyerik/jquery-upvote#7]
Is there any way to cancel action. Currently, I do cancellation by doing re-initialization and set the callback again.

**Comment by janosgyerik** [comment]
What exactly would you like to cancel? The buttons work as toggles, click again to flip the state. I'm not sure what behavior you're looking for.

**Comment by arieswandari** [comment]
I mean cancelling action without clicking. E.g user doing votes up, but backend process said its not valid and need to be cancelled (automatically,without clicking the button).

**Comment by janosgyerik** [comment]
Duplicate of #5
